version: "2.3"
services:     
  spring-boot-rest-docker-app:
    image: springboot
    build:
      context: ./
      dockerfile: DockerFile
    ports:
      - 8765:8080
    volumes:
      - /data/spring-boot-app
  mysqldb:
    image: mysql:5.7
    container_name: dbcontainer
    ports:
        - 3306:3306
    environment:
      - MYSQL_DATABASE=labAOS
      - MYSQL_USER=stefania
      - MYSQL_PASSWORD=stefania
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
    - /data/mysql
    - "/sql-scripts:/docker-entrypoint-initdb.d/"